### ISSUE TITLE
Make 3'rd party and Radix components to be run on ARM nodes

### ISSUE THREAD

**Issue by sveinpj** [equinor/radix-flux#2109]
Strategy to decide:
- Nodeselector (simple)
- affinity / antiaffinity

Components
- [x] azure-service-operator     
- [x] blob-csi-driver            
- [x] cert-manager               
- [x] external-secrets-operator  
- [x] grafana                    
- [x] ~~ingress-nginx~~
- [x] keda                       
- [x] kube-prometheus-stack      
- [x] kubernetes-replicator      
- [x] kured                      
- [x] (radix)prometheus-guard DEV  https://github.com/equinor/radix-flux/pull/2169     
- [x] (radix)prometheus-guard All envs
- [x] https://github.com/equinor/radix-acr-cleanup/issues/83       
- [x] https://github.com/equinor/radix-cicd-canary/issues/205          
- [x] radix-cluster-cleanup      
- [x] radix-cost-allocation      
- [x] radix-operator
- [x] radix-pipeline-runner
- [x] radix-tekton
- [x] radix-image-builder (ACR tasks)
- [x] radix-builder with buildah (build-kit)
- [x] radix-vulnerability-scanner
  - [x] fix database workflow service principals - https://github.com/equinor/radix-platform/issues/1421
- [x] ~~tekton-pipeline-runs~~           
- [x] velero, radix-velero-plugin
- [x] workload-identity-webhook

**Comment by emirgens** [comment]
Move tekton-pipeline-runs at a later stage
